# Generated by Django 2.2 on 2019-04-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menuItemName',
            field=models.CharField(default='small', max_length=63),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='small', max_length=63),
        ),
    ]
