# Generated by Django 2.2 on 2019-05-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190505_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isRejected',
            field=models.BooleanField(default=False),
        ),
    ]
