# Generated by Django 2.2 on 2019-05-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190505_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagePath',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
